### PR TITLE
Fix and enhancement for Next 16

### LINKED ISSUE #1022: Handle segment data in the incremental cache
See https://github.com/vercel/next.js/blob/2ed06f03e810b3a2dcec4b60a452621a08f4b068/packages/next/src/server/lib/incremental-cache/file-system-cache.ts#L204-L231

### LINKED ISSUE #1026: `fetchExternalImage` signature change -> e2e failure
The function takes 3 parameters since https://github.com/vercel/next.js/commit/8d415853f73c72263d24be3ea92b497d41f242f0

It cause the [e2e to fail](https://github.com/opennextjs/opennextjs-aws/actions/runs/18741263805/job/53458587617#step:12:19)

### PR DESCRIPTION
**Pull request by conico974**
Should fix most build failures in Next 16.
Support for incremental prefetching (Fix #1022)
Support for incremental prefetching in the cache interceptor
Fix #1026

### CODE REVIEW

**Comment by khuezy** [comment]
Do we have to handle the `middleware` => `proxy` renaming in 16?

**Comment by conico974** [comment]
> Do we have to handle the middleware => proxy renaming in 16?

Nope it doesn't change the name of the compiled file, but we have to update to Node 20 for e2e it seems....

File: packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts [hunk 1]
```diff
@@ -27,7 +27,8 @@ export async function optimizeImage(
   const { isAbsolute, href } = imageParams;
 
   const imageUpstream = isAbsolute
-    ? await fetchExternalImage(href)
+    ? //@ts-ignore
```
Comment (sommeeeer) [inline packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts]: Is this necessary? If so do an expect-error with description.

File: examples/app-router/app/og/opengraph-image.tsx [hunk 2]
```diff
@@ -31,6 +31,9 @@ export default async function Image() {
       // For convenience, we can re-use the exported opengraph-image
       // size config to also set the ImageResponse's width and height.
       ...size,
+      headers: {
+        "cache-control": "public, immutable, no-transform, max-age=31536000",
```
Comment (sommeeeer) [inline examples/app-router/app/og/opengraph-image.tsx:35]: Why did you set this?

File: examples/app-router/app/isr-data-cache/page.tsx [hunk 3]
```diff
@@ -4,7 +4,7 @@ async function getTime() {
   return new Date().toISOString();
 }
 
-const cachedTime = unstable_cache(getTime, { revalidate: false });
+const cachedTime = unstable_cache(getTime, ["getTime"], { revalidate: false });
```
Comment (sommeeeer) [inline examples/app-router/app/isr-data-cache/page.tsx:7]: Is it still called `unstable_cache`? Isnt it stable yet?

**Review by sommeeeer — CHANGES_REQUESTED** [review]
Very good job Nico! It seems to pass the E2E locally for me on Next 16. 

Just a few comments and also could you rename the middleware files to proxy in all the examples app. (`npx @next/codemod@canary middleware-to-proxy .`)

File: packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts (hunk 1 above)
Comment (vicb) [reply packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts]: Looks like it's related to #1026 (the signature changed with Next 16).
+1 to add a comment about that

File: packages/open-next/src/build/createAssets.ts [hunk 4]
```diff
@@ -169,6 +173,24 @@ export function createCacheAssets(options: buildHelper.BuildOptions) {
       logger.warn(`Skipping invalid cache file: ${cacheFilePath}`);
       return;
     }
+    const segments: Record<string, string> = {};
+
+    // If we have a meta file, and it contains segmentPaths, we need to add them to the cache file
+    if (
+      cacheFileMeta &&
+      Array.isArray(cacheFileMeta.segmentPaths) &&
```
Comment (vicb) [inline packages/open-next/src/build/createAssets.ts]:
```suggestion
      Array.isArray(cacheFileMeta?.segmentPaths) &&
```

Comment (vicb) [reply packages/open-next/src/build/createAssets.ts]: `cacheFileMeta.segmentPaths.length > 0` could also be skipped maybe

Comment (vicb) [reply packages/open-next/src/build/createAssets.ts]: Maybe something like:

```ts
const segments: Record<string, string> = Array.isArray(cacheFileMeta?.segmentPaths) ? 
  Object.fromEntries(cacheFileMeta.segmentPaths.map(...)) :
  {};
```

File: examples/app-router/app/isr-data-cache/page.tsx (hunk 3 above)
Comment (conico974) [reply examples/app-router/app/isr-data-cache/page.tsx:7]: Actually yeah, it will be superseded by `use cache`, but that's not the same thing

File: examples/app-router/app/og/opengraph-image.tsx (hunk 2 above)
Comment (conico974) [reply examples/app-router/app/og/opengraph-image.tsx:35]: Next does not automatically set the cache on this anymore. Need to test with `next start`

**Comment by khuezy** [comment]
Do we have any tests for `User-Agent`, someone reported that it gets dropped: [Discord](https://discord.com/channels/1283128968140161065/1288871672035803236/1434840309325365359)

Could be some weird delimiter character in the user agent that's causing the break, eg `;`

**Comment by vicb** [comment]
> Do we have any tests for `User-Agent`, someone reported that it gets dropped: [Discord](https://discord.com/channels/1283128968140161065/1288871672035803236/1434840309325365359)
> 
> Could be some weird delimiter character in the user agent that's causing the break, eg `;`

Is this related to this PR or should it be a different question/issue?

File: examples/app-pages-router/next.config.ts [hunk 5]
```diff
@@ -3,12 +3,8 @@ import type { NextConfig } from "next";
 const nextConfig: NextConfig = {
   poweredByHeader: false,
   cleanDistDir: true,
-  transpilePackages: ["@example/shared"],
+  // transpilePackages: ["@example/shared"],
```
Comment (vicb) [inline examples/app-pages-router/next.config.ts]: Should this be removed completely?

**Comment by khuezy** [comment]
It's unrelated, we can continue the discussion when the person opens a ticket.

File: examples/app-router/app/api/after/revalidate/route.ts [hunk 6]
```diff
@@ -6,7 +6,8 @@ export function POST() {
     () =>
       new Promise<void>((resolve) =>
         setTimeout(() => {
-          revalidateTag("date");
+          // We want to expire the "date" tag immediately
+          revalidateTag("date", { expire: 0 });
```
Comment (vicb) [inline examples/app-router/app/api/after/revalidate/route.ts]: nit to make things clearer:

```suggestion          
          revalidateTag("date", { 
            // We want to expire the "date" tag immediately
            expire: 0 
          });
```

File: examples/app-router/proxy.ts [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import type { NextRequest } from "next/server";
 import { NextResponse } from "next/server";
 
-export function middleware(request: NextRequest) {
+export default function middleware(request: NextRequest) {
```
Comment (vicb) [inline examples/app-router/proxy.ts]: nit: adhere to [Next convetions](https://nextjs.org/docs/app/getting-started/proxy#example)
```suggestion
export default function proxy(request: NextRequest) {
```

File: packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts [hunk 8]
```diff
@@ -27,7 +27,8 @@ export async function optimizeImage(
   const { isAbsolute, href } = imageParams;
 
   const imageUpstream = isAbsolute
-    ? await fetchExternalImage(href)
+    ? //@ts-expect-error - fetchExternalImage signature has changed in Next.js 16, it has an extra boolean parameter.
+      await fetchExternalImage(href)
```
Comment (vicb) [inline packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts:32]: Ref: https://github.com/vercel/next.js/blob/bfe2ab4/packages/next/src/server/image-optimizer.ts#L711

Do we want to include that ref in the comment and explain why we choose
- dangerouslyAllowLocalIP = false 
- count = 3 
with Next 16?

File: packages/tests-e2e/tests/appRouter/og.test.ts [hunk 9]
```diff
@@ -49,8 +49,8 @@ test("next/og (vercel/og) to work in API route", async ({ request }) => {
   const response = await request.get("api/og?title=opennext");
   expect(response.status()).toBe(200);
   expect(response.headers()["content-type"]).toBe("image/png");
-  expect(response.headers()["cache-control"]).toBe(
-    "public, immutable, no-transform, max-age=31536000",
-  );
+  // expect(response.headers()["cache-control"]).toBe(
```
Comment (vicb) [inline packages/tests-e2e/tests/appRouter/og.test.ts]: what do we want to do with those expectations?

File: pnpm-workspace.yaml [hunk 10]
```diff
@@ -3,7 +3,7 @@ packages:
   - "packages/*"
 
 catalog:
-  next: 15.4.2
+  next: 16.0.0
```
Comment (vicb) [inline pnpm-workspace.yaml]: Update to 16.0.1

File: packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts (hunk 8 above)
Comment (conico974) [reply packages/open-next/src/adapters/plugins/image-optimization/image-optimization.replacement.ts:32]: I don't think we need to explain why really. This one probably need some big refactor at one point anyway

File: packages/tests-e2e/tests/appRouter/og.test.ts (hunk 9 above)
Comment (conico974) [reply packages/tests-e2e/tests/appRouter/og.test.ts]: If next doesn't do it anymore by default, we should remove it (just checked, that's the case in `next start`).
But I think it's still a good idea to test to add them manually. I keep it in one and not in the other

File: .changeset/thirty-bears-tell.md [hunk 11]
```diff
@@ -0,0 +1,5 @@
+---
+"@opennextjs/aws": minor
```
Comment (vicb) [inline .changeset/thirty-bears-tell.md:2]: Should this PR be a major change and drop support for Next < 14 ?

**Comment by vicb** [comment]
Changes LGTM
~it looks like the lock file is not updated to 16.0.1~ added a fixup commit

File: .changeset/thirty-bears-tell.md (hunk 11 above)
Comment (conico974) [reply .changeset/thirty-bears-tell.md:2]: I don't think we should, this doesn't change much for earlier versions. Only big difference being Node 20, but I didn't change the esbuild target on purpose. Virtually no difference for earlier versions

Comment (vicb) [reply .changeset/thirty-bears-tell.md:2]: Makes sense !

**Comment by sommeeeer** [comment]
> @sommeeeer I can't retrieve what your requested change was?

It was just this: https://github.com/opennextjs/opennextjs-aws/pull/1029#pullrequestreview-339103772

**Review by sommeeeer — APPROVED** [review]
LGTM, gj on this one!
