### PR TITLE
Fix fallback false

### LINKED ISSUE #677: Pages Router catchAll route with `fallback:false` cause 404 on api route
My company has a large project built with Next.js 12. As Next.js 12 is now outdated, we updated our project to Next.js 14 while keeping the Pages Router structure. Previously, we were using cdk-nextjs-standalone to deploy the application to AWS, and everything was working fine.
However, after upgrading to Next.js 14 and deploying, our API routes topped functioning. To resolve this, we decided to migrate to the SST framework (v3). Despite completing the migration and configuration, our API routes are still not working and continue sending us to 404 page.

```
Versions:
Next.js: v14.2.20
SST: v3.3.65
OpenNext.js: 3.2.2
```
Steps Taken:

Updated Next.js from v12 to v14 (keeping the Pages Router structure).
Migrated deployment from cdk-nextjs-standalone to SST (v3).
Configured the SST project following the documentation.
Even after successfully deploying the project with SST v3, our API routes are unresponsive.

**Another point to add is that we performed a fresh install deployment of Next.js v15 using the Pages Router, and the APIs are not working either.**

### PR DESCRIPTION
**Pull request by conico974**
Dynamic route with fallback false can wrongly intercept and return 404 for routes that intersect with them.

Fix #677 and https://github.com/opennextjs/opennextjs-cloudflare/issues/611

### CODE REVIEW

File: packages/open-next/src/core/requestHandler.ts [hunk 1]
```diff
@@ -221,43 +221,73 @@ async function processRequest(
   // https://github.com/dougmoscrop/serverless-http/issues/227
   delete req.body;
 
+  // Here we try to apply as much request metadata as possible
+  // We apply every metadata from `resolve-routes` https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/router-utils/resolve-routes.ts
+  // and `router-server` https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/router-server.ts
```
Comment (vicb) [inline packages/open-next/src/core/requestHandler.ts:226]: nit use sha1 refs?

File: packages/open-next/src/core/requestHandler.ts [hunk 2]
```diff
@@ -221,43 +221,73 @@ async function processRequest(
...
+    return;
+  }
+  try {
+    await requestHandler({
+      ...routingResult,
+      invokeOutput: routingResult.resolvedRoutes[index].route,
+      ...metadata,
+    })(req, res);
+  } catch (e: any) {
+    if (e.constructor.name === "NoFallbackError") {
```
Comment (vicb) [inline packages/open-next/src/core/requestHandler.ts:289]: could that cause issue with minification?

Comment (conico974) [reply packages/open-next/src/core/requestHandler.ts:289]: It does work in cloudflare in preview

Comment (khuezy) [reply packages/open-next/src/core/requestHandler.ts:289]: If this is a concern, there is a `keep_classname` option in the webpack config.

**Review by vicb — APPROVED** [review]

**Comment by sommeeeer** [comment]
> Same issue as the referenced issue:
> [opennextjs/opennextjs-cloudflare#611](https://github.com/opennextjs/opennextjs-cloudflare/issues/611)

You reproduction doesn't have `dynamicParams` in it. Seems to be a blank project. Maybe you forgot to push a commit?

**Comment by lauri865** [comment]
Sorry, correction, the original issue seems to be fixed. Repro doesn't reproduce it anymore, but we seem to be hitting a new issue it seems (fallback rewrite doesn't get triggered, and we end up with 404 in a different scenario). I will see if I can create a new reproduction soon.

**Comment by lauri865** [comment]
New reproduction committed.

`pnpm dev / start` work just fine (shows this issue when you navigate to any non-existing page, e.g. http://localhost:3000/abc123`

If no `export const dynamicParams = false;`:
`pnpm preview` shows content page (/test) for any non-existing path

If `export const dynamicParams = false;` is present:
`pnpm preview` shows 404 also for static path /test that should exist, and the fallback doesn't work for any non-existing path.

**Comment by lauri865** [comment]
New reproduction committed: https://github.com/lauri865/opennext-routes-repro

`pnpm dev / start` work just fine (shows this Github issue when you navigate to any non-existing page, e.g. http://localhost:3000/abc123

If `export const dynamicParams = false;` is present:
`pnpm preview` shows 404 also for static path /test that should exist, and the fallback rewrite in `next.config` doesn't work for any non-existing path.

**Comment by conico974** [comment]
@lauri865 You need an incrementalCache in your `open-next.config.ts`

**Comment by lauri865** [comment]
We have`staticAssetsIncrementalCache` in our production config, but facing the same issue. Do we need something else? Our site us fully static.

**Comment by conico974** [comment]
@lauri865 Create an issue with a link to the repro, then

**Comment by lauri865** [comment]
@conico974, I did, it's referenced as fixed by this PR. Which it seems to be not. Should I open another PR?

**Comment by conico974** [comment]
@lauri865 Yeah, that's not the same issue: 
> Sorry, correction, the original issue seems to be fixed. Repro doesn't reproduce it anymore

**Comment by lauri865** [comment]
Opened a new issue here with a reproduction: https://github.com/opennextjs/opennextjs-cloudflare/issues/682
